version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  release-build:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assemblepilot 
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      - run:
          name: testing command
          command: |
              .circleci/UploadToAppcenter.sh && ls /

workflows:
  test-and-build:
    jobs:
      - release-build

